### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by edgarrmondragon** [Matatika/tap-shopify#10]
This tap is constrained to Python < 3.11. Would be nice to support it.

https://github.com/Matatika/tap-shopify/blob/8c523679b0d52241e9ef5685b6d0c02c513db973/pyproject.toml#L13

**Comment by ReubenFrankel** [comment]
Thanks! @edgarrmondragon

**Comment by ReubenFrankel** [comment]
Released in [`v0.2.0`](https://github.com/Matatika/tap-shopify/releases/tag/v0.2.0)
