### ISSUE TITLE
Should the transactions stream be incremental?

### ISSUE THREAD

**Issue by pnadolny13** [Matatika/tap-shopify#26]
It looks like the child transactions stream could probably be incremental based on the order updated_at date since the order will always get updated when a transaction is added and I think transactions are immutable. I dont see it explicitly documented anywhere but this comment suggests it https://community.shopify.com/c/customers-discounts-and-orders/does-creating-a-transaction-update-the-order-s-updated-at/m-p/1321740/highlight/true#M2521 and the API doesnt have a way to update so I think its a safe assumption.

@ReubenFrankel any idea if this is true?

**Comment by pnadolny13** [comment]
On second look it seems like maybe this is already the case 🤔

**Comment by ReubenFrankel** [comment]
@pnadolny13 As a child stream of `OrdersStream`, `TransactionsStream` is implicitly incremental already, given that transactions will only sync when there are changes to orders and a new transaction will update the associated order `updated_at` timestamp.

We could probably additional incremental logic specifically for `TransactionStream` using [`since_id`](https://shopify.dev/docs/api/admin-rest/2023-10/resources/transaction#get-orders-order-id-transactions), but not sure this is that necessary given that [an order can have no more than 100 associated transactions](https://shopify.dev/docs/api/admin-rest/2023-10/resources/transaction) anyway...

**Comment by pnadolny13** [comment]
@ReubenFrankel thanks for the info! I understand whats going on now. The reason I thought it wasnt incremental is because it doesnt set the `replication_method` on the stream and the SDK defaults to full table. It looks like the custom logic in `tap_shopifyStream` handles the incremental parameters but do you know if its safe to not have the replication method set? I wonder if the SDK is using it for anything important in this case.

**Comment by ReubenFrankel** [comment]
@pnadolny13 I could be wrong but I don't think not having a `replication_method` set is a problem here, since `TransactionsStream` in a vacuum is not incremental (for any changed order, **all** associated transactions will be extracted). Thinking about it now, I'm hesitant to even label it as incremental at all - it just exhibits incremental behaviour by proxy due to the way transactions and orders interact. If we wanted to make it truly incremental, we could implement `since_id` as above.

**Comment by pnadolny13** [comment]
@ReubenFrankel yeah that makes total sense. Thanks
